all: 
	g++ np_simple.cpp np_simple.h -o np_simple
	g++ np_single_proc.cpp np_single_proc.h -o np_single_proc
	g++ np_multi_proc.cpp -o np_multi_proc
clean:
	@rm np_simple
	@rm np_single_proc
	@rm np_multi_proc

